### ISSUE TITLE
ynpm使用问题

### ISSUE THREAD

**Issue by BoyuZhou** [iuap-design/yon#1]
当我在脚本中使用ynpm install时，下载完成后，会终止我的脚本其他命令执行。npm install 没有这个问题。

**Comment by onvno** [comment]
@BoyuZhou 目前测试本地sh脚本，jenkins执行sh脚本均未复现问题。升级0.2.2版本处理了正确结束任务退出进程的状态，由1改为0.可以测试下新版。
