### ISSUE TITLE
安装 Package 时没有自动安装这个的依赖

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/yon#2]
>  安装 Package 时由于缺少 postinstall 操作，导致没有自动安装这个包的依赖，出现对应的包下载之后无法使用的问题。

![image](https://user-images.githubusercontent.com/8686869/37447932-3ab9284a-285f-11e8-93de-7afc9cedf785.png)

**Comment by jonyshi** [comment]
已经解决
