### ISSUE TITLE
授权发包和发包权限管理待优化

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/yon#4]
## TODO

1、目前发包授权方式是 [自定义密码、密码base64、设置 auth的方式进行](https://github.com/iuap-design/ynpm-tool/wiki)，这种方式比较繁琐，也不够直观。需要通过云端页面注册的方式直观管理。

2、通过 `JSON` 数据的方式维护权限列表的方式不安全，需要起一个轻量的数据库进行维护。

**Comment by jonyshi** [comment]
目前用有空间加密授权，不需要人工配置了。
