### ISSUE TITLE
云平台包管理中心 PMC 项目计划

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/yon#5]
# 挖河道，引活水，做新时代的大禹

## 背景

在端上，结合不同的设计项目实践，会有大量和业务相关的 UI组件（基础组件、业务组件）、工具包、JS-SDK、最佳实践工程、页面模板等资源产出。

为了实现在事业部乃至更大范围的代码资产的可管理性和可复用性，准备筹划建立【云平台包管理中心 PMC】，通过制定相关的包管理规范、搭建可上传下载的机制，实现大范围海量资源的上传、复用、查找、技术支持等能力，也能在一定程度实现技术人员的个人影响力和价值体现。

## 计划

**A1：搭建镜像仓库**
- [x] [在新的机器上重新部署 Nexus，作为镜像仓库的管理后端（前端页面重写）。]()
- [ ] [权限要和友户通打通；通过本地生成 SSH Key，并将 Public Key 配置在开发者中心的形式取得发包权限]()
- [ ] [访问入口在开发者中心]()

**A2：制定包的开发规范、上传下载等使用规则及使用流程**
- [ ] [明确开发规范（包括如何开发、如何上传、如何下载使用等）]()
- [ ] [发布的多端资源包要进行分类：SDK、UI 组件、页面模板zip包、node 模块等]()
- [ ] [优化 ynpm CLI 命令行工具，体验和 NPM 靠近，要增加进度等提示]()

**A3：实现对镜像仓库资源的可视化查找和预览**

- [ ] [页面重构工作：首页、检索页（列表）、组件详情页]()

**A4：集成和推广**
- [ ] [和 uba-gui 集成]()
- [ ] [对内的推广和使用引导]()

## 细节和任务

待拆解。

**Comment by kvkens** [comment]
还有一点，不光作为cli使用，还需要按照api的方式使用，uba-gui依赖ynpm可以调用其源码来运行上述功能

**Comment by GuoYongfeng** [comment]
@jonyshi 这种得参考 github Open api 来提供 package 信息的对接查找接口。

**Comment by fridaydream** [comment]
上面功能已经全部实现。 @GuoYongfeng @kvkens
